version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN} 
      - OWNER_ID=${OWNER_ID} 
      - LAVALINK_HOST=${LAVALINK_HOST} 
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD} 
      - LAVALINK_PORT=${LAVALINK_PORT} 
    restart: unless-stopped  # Restart bot if it crashes